pipeline {
    agent {
        node {
            label 'worker' 
        }
   }
   environment {
     BRANCH_NAME = "${GIT_BRANCH.split("/")[1]}"
  }

    stages {
        stage('Docker login') {
             steps {
                withCredentials([usernamePassword(credentialsId: 'dockerHubCreds', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_TOKEN')]) {
                sh 'echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin'
                }
            }
        }
        stage('Docker build') {
            steps{
                sh 'docker build -t terraform .'
            }
        }
        stage('Docker tag and push') {
            steps {
                sh """
                    docker tag terraform denisvoznik/terraform-dz:${BRANCH_NAME}
                    docker push denisvoznik/terraform-dz:${BRANCH_NAME}
                """
            }
        }
    }
}
