pipeline {
    agent {
        node {
            label 'worker' 
        }
   }

   stages {
        stage('Docker login') {
             steps {
                withCredentials([usernamePassword(credentialsId: 'dockerHubCreds', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_TOKEN')]) {
                sh 'echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin'
                }
            }
        }
        stage('Docker build') {
            steps{
                sh 'docker build -t terraform .'
            }
        }
        stage('Docker tag and push') {
            steps {
                sh """
                    docker tag denisvoznik/terraform-dz:${env.BRANCH_NAME}
                    docker push denisvoznik/terraform-dz:${env.BRANCH_NAME}
                """
            }
        }
    }
    post { 
        success { 
            githubNotify status: "SUCCESS", description: 'Success status'
        }
        failure {
            githubNotify status: "FAILURE", description: 'Failure status'
        }
    }
}
